Repository propaganda-and-fabrication/outsourcing-app, pull requests merged in 2025-03, with the labels that each got.

#8 Fix: Response 타입 문제 및 BaseTime 오타 수정
  src/main/java/com/outsourcing/common/entity/BaseTime.java
  src/main/java/com/outsourcing/common/response/ErrorResponse.java
  src/main/java/com/outsourcing/common/response/Response.java
  src/main/java/com/outsourcing/common/response/SuccessResponse.java
  src/main/java/com/outsourcing/common/response/ValidationErrorResponse.java
Labels: 🐛 bug

#10 Feat: `User` 및 `User` 관련 엔티티 생성
  src/main/java/com/outsourcing/common/exception/ErrorCode.java
  src/main/java/com/outsourcing/domain/user/dto/response/CustomerResponse.java
  src/main/java/com/outsourcing/domain/user/entity/Address.java
  src/main/java/com/outsourcing/domain/user/entity/Customer.java
  src/main/java/com/outsourcing/domain/user/entity/Owner.java
  src/main/java/com/outsourcing/domain/user/entity/User.java
  src/main/java/com/outsourcing/domain/user/enums/AddressStatus.java
  src/main/java/com/outsourcing/domain/user/enums/UserRole.java
  src/main/resources/application.yml
Labels: ✨ feat

#12 feat : 스토어 엔티티 및 관련 이넘 생성
  src/main/java/com/outsourcing/domain/store/entitiy/Store.java
  src/main/java/com/outsourcing/domain/store/enums/StoreStatus.java
Labels: ✨ feat

#16 Feat: 유저 인증/인가 구현
  build.gradle
  src/main/java/com/outsourcing/common/exception/ErrorCode.java
  src/main/java/com/outsourcing/common/exception/GlobalControllerAdvice.java
  src/main/java/com/outsourcing/common/filter/JwtAuthenticationFilter.java
  src/main/java/com/outsourcing/common/filter/JwtAuthorizationFilter.java
  src/main/java/com/outsourcing/common/response/ErrorResponse.java
  src/main/java/com/outsourcing/common/response/Response.java
  src/main/java/com/outsourcing/common/util/jwt/JwtTokenProvider.java
  src/main/java/com/outsourcing/config/RedisConfig.java
  src/main/java/com/outsourcing/config/SecurityConfig.java
  src/main/java/com/outsourcing/domain/auth/controller/AuthController.java
  src/main/java/com/outsourcing/domain/auth/dto/request/CustomerSignUpRequest.java
  src/main/java/com/outsourcing/domain/auth/dto/request/LogoutRequest.java
  src/main/java/com/outsourcing/domain/auth/dto/request/OwnerSignUpRequest.java
  src/main/java/com/outsourcing/domain/auth/dto/request/SignInRequest.java
  src/main/java/com/outsourcing/domain/auth/dto/request/TokenReissueRequest.java
  src/main/java/com/outsourcing/domain/auth/dto/response/TokenResponse.java
  src/main/java/com/outsourcing/domain/auth/entity/RefreshToken.java
  src/main/java/com/outsourcing/domain/auth/repository/RefreshTokenRepository.java
  src/main/java/com/outsourcing/domain/auth/repository/RefreshTokenRepositoryImpl.java
  src/main/java/com/outsourcing/domain/auth/service/AuthService.java
  src/main/java/com/outsourcing/domain/auth/service/CustomUserDetails.java
  src/main/java/com/outsourcing/domain/auth/service/CustomUserDetailsService.java
  src/main/java/com/outsourcing/domain/user/dto/UserInfo.java
  src/main/java/com/outsourcing/domain/user/entity/Customer.java
  src/main/java/com/outsourcing/domain/user/enums/UserRole.java
  src/main/java/com/outsourcing/domain/user/repository/UserRepository.java
Labels: ✨ feat

#17 Chore: 응답 구조 변경
  src/main/java/com/outsourcing/common/exception/BaseException.java
  src/main/java/com/outsourcing/common/exception/ErrorCode.java
  src/main/java/com/outsourcing/common/exception/ErrorCodeDto.java
  src/main/java/com/outsourcing/common/exception/GlobalControllerAdvice.java
  src/main/java/com/outsourcing/common/exception/ValidationErrorDto.java
  src/main/java/com/outsourcing/common/filter/JwtAuthenticationFilter.java
  src/main/java/com/outsourcing/common/filter/JwtAuthorizationFilter.java
  src/main/java/com/outsourcing/common/response/ErrorResponse.java
  src/main/java/com/outsourcing/common/response/Response.java
  src/main/java/com/outsourcing/common/response/SuccessResponse.java
  src/main/java/com/outsourcing/domain/auth/service/AuthService.java
Labels: ⚙️ chore

#18 Feat: Customer 관련 서비스 구현
  .gitignore
  src/main/java/com/outsourcing/common/exception/ErrorCode.java
  src/main/java/com/outsourcing/domain/auth/controller/AuthController.java
  src/main/java/com/outsourcing/domain/auth/repository/RefreshTokenRepositoryImpl.java
  src/main/java/com/outsourcing/domain/auth/service/AuthService.java
  src/main/java/com/outsourcing/domain/auth/service/CustomUserDetailsService.java
  src/main/java/com/outsourcing/domain/user/controller/CustomerController.java
  src/main/java/com/outsourcing/domain/user/dto/request/customer/AddAddressRequest.java
  src/main/java/com/outsourcing/domain/user/dto/request/customer/DeleteCustomerRequest.java
  src/main/java/com/outsourcing/domain/user/dto/request/customer/UpdateAddressRequest.java
  src/main/java/com/outsourcing/domain/user/dto/request/customer/UpdateNicknameRequest.java
  src/main/java/com/outsourcing/domain/user/dto/request/customer/UpdatePasswordRequest.java
  src/main/java/com/outsourcing/domain/user/dto/request/customer/UpdatePhoneNumberRequest.java
  src/main/java/com/outsourcing/domain/user/dto/request/customer/UpdateProfileUrlRequest.java
  src/main/java/com/outsourcing/domain/user/dto/response/CustomerResponse.java
  src/main/java/com/outsourcing/domain/user/dto/response/GetAllAddressResponse.java
  src/main/java/com/outsourcing/domain/user/entity/Address.java
  src/main/java/com/outsourcing/domain/user/entity/Customer.java
  src/main/java/com/outsourcing/domain/user/entity/User.java
  src/main/java/com/outsourcing/domain/user/repository/AddressRepository.java
  src/main/java/com/outsourcing/domain/user/repository/CustomerRepository.java
  src/main/java/com/outsourcing/domain/user/repository/UserRepository.java
  src/main/java/com/outsourcing/domain/user/service/CustomerService.java
Labels: ✨ feat

#23 Refactor: `Auth` 리팩토링
  src/main/java/com/outsourcing/domain/auth/controller/AuthOwnerController.java
  src/main/java/com/outsourcing/domain/auth/service/AuthCommonService.java
  src/main/java/com/outsourcing/domain/auth/service/AuthCustomerService.java
  src/main/java/com/outsourcing/domain/auth/service/AuthOwnerService.java
  src/main/java/com/outsourcing/domain/user/service/CustomerService.java
  src/main/java/com/outsourcing/domain/user/service/OwnerService.java
Labels: 🔄 refactor

#28 Refactor: auth, user 패키지 리팩토링
  src/main/java/com/outsourcing/domain/auth/controller/AuthCustomerController.java
  src/main/java/com/outsourcing/domain/auth/controller/AuthOwnerController.java
  src/main/java/com/outsourcing/domain/auth/dto/request/CustomerSignUpRequest.java
  src/main/java/com/outsourcing/domain/auth/dto/request/OwnerSignUpRequest.java
  src/main/java/com/outsourcing/domain/auth/service/AuthCustomerService.java
  src/main/java/com/outsourcing/domain/auth/service/AuthOwnerService.java
  src/main/java/com/outsourcing/domain/user/controller/CustomerController.java
  src/main/java/com/outsourcing/domain/user/controller/OwnerController.java
  src/main/java/com/outsourcing/domain/user/dto/AddressDto.java
  src/main/java/com/outsourcing/domain/user/dto/request/UpdatePhoneNumberRequest.java
  src/main/java/com/outsourcing/domain/user/dto/request/customer/AddAddressRequest.java
  src/main/java/com/outsourcing/domain/user/dto/request/customer/UpdateAddressRequest.java
  src/main/java/com/outsourcing/domain/user/dto/response/GetAllAddressResponse.java
  src/main/java/com/outsourcing/domain/user/entity/Address.java
  src/main/java/com/outsourcing/domain/user/entity/Customer.java
  src/main/java/com/outsourcing/domain/user/enums/AddressStatus.java
  src/main/java/com/outsourcing/domain/user/repository/AddressRepository.java
  src/main/java/com/outsourcing/domain/user/service/CustomerService.java
  src/main/java/com/outsourcing/domain/user/service/OwnerService.java
Labels: 🔄 refactor

#31 Fix: 주소 변경 및 삭제 수정
  src/main/java/com/outsourcing/common/exception/ErrorCode.java
  src/main/java/com/outsourcing/domain/user/service/CustomerService.java
Labels: 🐛 bug

#27 Feat: 메뉴 도메인 구조 설정 및 기본 클래스 구현
  src/main/java/com/outsourcing/common/exception/ErrorCode.java
  src/main/java/com/outsourcing/domain/menu/controller/MenuController.java
  src/main/java/com/outsourcing/domain/menu/dto/request/CreateMenuRequest.java
  src/main/java/com/outsourcing/domain/menu/dto/request/UpdateMenuRequest.java
  src/main/java/com/outsourcing/domain/menu/dto/response/CustomerMenuResponse.java
  src/main/java/com/outsourcing/domain/menu/dto/response/OwnerMenuResponse.java
  src/main/java/com/outsourcing/domain/menu/entity/Menu.java
  src/main/java/com/outsourcing/domain/menu/enums/MenuStatus.java
  src/main/java/com/outsourcing/domain/menu/repository/MenuRepository.java
  src/main/java/com/outsourcing/domain/menu/service/MenuService.java
  src/main/java/com/outsourcing/domain/order/entity/Order.java
  src/main/java/com/outsourcing/domain/store/dto/response/StoreCustomerResponse.java
  src/main/java/com/outsourcing/domain/store/dto/response/StoreOwnerResponse.java
  src/main/java/com/outsourcing/domain/store/entitiy/Store.java
  src/main/java/com/outsourcing/domain/store/entity/Store.java
  src/main/java/com/outsourcing/domain/store/repository/StoreRepository.java
Labels: ✨ feat

#36 Chore: 성공 응답 시 메시지 제거
  src/main/java/com/outsourcing/common/response/Response.java
  src/main/java/com/outsourcing/common/response/SuccessResponse.java
  src/main/java/com/outsourcing/domain/auth/controller/AuthCommonController.java
  src/main/java/com/outsourcing/domain/auth/controller/AuthCustomerController.java
  src/main/java/com/outsourcing/domain/auth/controller/AuthOwnerController.java
  src/main/java/com/outsourcing/domain/user/controller/CustomerController.java
  src/main/java/com/outsourcing/domain/user/controller/OwnerController.java
Labels: ⚙️ chore

#37 Chore: aws 의존성 추가 및 S3 설정
  build.gradle
  src/main/java/com/outsourcing/common/util/s3/S3Config.java
  src/main/java/com/outsourcing/domain/menu/controller/MenuController.java
  src/main/java/com/outsourcing/domain/order/entity/Order.java
  src/main/java/com/outsourcing/domain/order/entity/OrderItem.java
Labels: ⚙️ chore

#39 Feat: S3 이미지 업로드 구현
  src/main/java/com/outsourcing/common/exception/ErrorCode.java
  src/main/java/com/outsourcing/common/storage/StorageService.java
  src/main/java/com/outsourcing/common/storage/controller/FileUploadController.java
  src/main/java/com/outsourcing/common/storage/dto/response/UploadResponse.java
  src/main/java/com/outsourcing/common/storage/enums/UploadType.java
  src/main/java/com/outsourcing/common/storage/s3/S3StorageService.java
  src/main/java/com/outsourcing/common/util/FileUtils.java
  src/main/java/com/outsourcing/config/S3Config.java
  src/main/java/com/outsourcing/config/SecurityConfig.java
Labels: ✨ feat

#43 Refactor: auth 패키지 및 security 관련 리팩토링
  src/main/java/com/outsourcing/common/constant/Const.java
  src/main/java/com/outsourcing/common/exception/ErrorCode.java
  src/main/java/com/outsourcing/common/filter/JwtAuthenticationFilter.java
  src/main/java/com/outsourcing/common/filter/JwtAuthorizationFilter.java
  src/main/java/com/outsourcing/common/handler/CustomAccessDeniedHandler.java
  src/main/java/com/outsourcing/common/handler/CustomAuthenticationEntryPoint.java
  src/main/java/com/outsourcing/config/SecurityConfig.java
  src/main/java/com/outsourcing/domain/auth/controller/AuthCommonController.java
  src/main/java/com/outsourcing/domain/auth/dto/request/LogoutRequest.java
Labels: 🔄 refactor

#45 Feat: 이미지 리사이징 구현
  build.gradle
  src/main/java/com/outsourcing/common/exception/ErrorCode.java
  src/main/java/com/outsourcing/common/storage/controller/FileUploadController.java
  src/main/java/com/outsourcing/common/storage/service/StorageService.java
  src/main/java/com/outsourcing/common/storage/service/s3/S3StorageService.java
  src/main/java/com/outsourcing/common/util/FileUtils.java
Labels: ✨ feat

#46 Feat: 이미지 다중 업로드 구현
  src/main/java/com/outsourcing/common/exception/ErrorCode.java
  src/main/java/com/outsourcing/common/storage/controller/FileUploadController.java
  src/main/java/com/outsourcing/common/storage/dto/response/MultipleUploadResponse.java
  src/main/java/com/outsourcing/common/storage/service/StorageService.java
  src/main/java/com/outsourcing/common/storage/service/s3/S3StorageService.java
Labels: ✨ feat

#48 Chore: properties 빈 등록을 위한 `PropertyConfig` 생성 후 적용
  .gitignore
  src/main/java/com/outsourcing/config/PropertyConfig.java
  src/main/java/com/outsourcing/config/SecurityConfig.java
Labels: ⚙️ chore

#53 Refactor: `Auth` 관련 리팩토링
  src/main/java/com/outsourcing/domain/auth/repository/RefreshTokenRepository.java
  src/main/java/com/outsourcing/domain/auth/repository/RefreshTokenRepositoryImpl.java
  src/main/java/com/outsourcing/domain/auth/service/AuthCommonService.java
  src/main/java/com/outsourcing/domain/auth/service/AuthCustomerService.java
  src/main/java/com/outsourcing/domain/user/entity/Owner.java
  src/main/java/com/outsourcing/domain/user/entity/User.java
  src/main/java/com/outsourcing/domain/user/service/CustomerService.java
  src/main/java/com/outsourcing/domain/user/service/OwnerService.java
Labels: 🔄 refactor

#54 Refactor: `User` 관련 리팩토링
  src/main/java/com/outsourcing/domain/auth/service/AuthCommonService.java
  src/main/java/com/outsourcing/domain/user/controller/CustomerController.java
  src/main/java/com/outsourcing/domain/user/controller/OwnerController.java
  src/main/java/com/outsourcing/domain/user/dto/request/DeleteUserRequest.java
  src/main/java/com/outsourcing/domain/user/service/CustomerService.java
  src/main/java/com/outsourcing/domain/user/service/OwnerService.java
Labels: 🔄 refactor

#55 Refactor: 객체의 id 값을 응답 필드에 추가
  src/main/java/com/outsourcing/domain/user/dto/response/CustomerResponse.java
  src/main/java/com/outsourcing/domain/user/dto/response/OwnerResponse.java
Labels: 🔄 refactor

#58 Refactor: 다중 파일 업로드 시 최대 3개까지 가능하도록 수정
  src/main/java/com/outsourcing/common/constant/Const.java
  src/main/java/com/outsourcing/common/exception/ErrorCode.java
  src/main/java/com/outsourcing/common/filter/JwtAuthenticationFilter.java
  src/main/java/com/outsourcing/common/storage/controller/FileUploadController.java
  src/main/java/com/outsourcing/common/util/jwt/JwtTokenProvider.java
  src/main/java/com/outsourcing/domain/user/controller/CustomerController.java
  src/main/java/com/outsourcing/domain/user/entity/Owner.java
Labels: 🔄 refactor

#40 feat: 메뉴 조회 기능 추가, 메뉴 수정/삭제 API 개선 및 조회 로직 최적화
  src/main/java/com/outsourcing/common/exception/ErrorCode.java
  src/main/java/com/outsourcing/domain/menu/controller/MenuController.java
  src/main/java/com/outsourcing/domain/menu/dto/request/UpdateMenuDetailsRequest.java
  src/main/java/com/outsourcing/domain/menu/dto/request/UpdateMenuRequest.java
  src/main/java/com/outsourcing/domain/menu/dto/response/CustomerMenuResponse.java
  src/main/java/com/outsourcing/domain/menu/dto/response/OwnerMenuResponse.java
  src/main/java/com/outsourcing/domain/menu/entity/Menu.java
  src/main/java/com/outsourcing/domain/menu/enums/MenuStatus.java
  src/main/java/com/outsourcing/domain/menu/repository/MenuRepository.java
  src/main/java/com/outsourcing/domain/menu/service/MenuService.java
  src/main/java/com/outsourcing/domain/order/service/OrderService.java
  src/main/resources/application.yml
Labels: ✨ feat

#62 Refactor: `SecurityConfig` 설정 추가
  src/main/java/com/outsourcing/config/SecurityConfig.java
  src/main/java/com/outsourcing/domain/auth/controller/AuthUserController.java
  src/main/java/com/outsourcing/domain/auth/service/AuthUserService.java
Labels: 🔄 refactor

#63 Refactor: user 패키지 내 사용하지 않는 필드 및 메서드 제거
  src/main/java/com/outsourcing/domain/user/repository/CustomerRepository.java
  src/main/java/com/outsourcing/domain/user/repository/OwnerRepository.java
  src/main/java/com/outsourcing/domain/user/service/CustomerService.java
  src/main/java/com/outsourcing/domain/user/service/OwnerService.java
Labels: 🔄 refactor

#65 Test: OwnerService 테스트 코드 작성
  src/test/java/com/outsourcing/domain/user/service/OwnerServiceTest.java
Labels: 🧪 test

#67 Test: `CustomerService` 테스트 코드 작성
  src/main/java/com/outsourcing/domain/user/service/CustomerService.java
  src/test/java/com/outsourcing/domain/user/service/CustomerServiceTest.java
Labels: 🧪 test

#71 feat : 리뷰 및 대댓리뷰 기능 추가.
  src/main/java/com/outsourcing/common/exception/ErrorCode.java
  src/main/java/com/outsourcing/config/SecurityConfig.java
  src/main/java/com/outsourcing/domain/order/controller/OwnerOrderController.java
  src/main/java/com/outsourcing/domain/order/controller/UserOrderController.java
  src/main/java/com/outsourcing/domain/order/repository/OrderRepository.java
  src/main/java/com/outsourcing/domain/order/service/OwnerOrderService.java
  src/main/java/com/outsourcing/domain/order/service/UserOrderService.java
  src/main/java/com/outsourcing/domain/review/controller/ReviewController.java
  src/main/java/com/outsourcing/domain/review/controller/ReviewReplyController.java
  src/main/java/com/outsourcing/domain/review/dto/request/ReviewReplyRequest.java
  src/main/java/com/outsourcing/domain/review/dto/request/ReviewReplyUpdateRequest.java
  src/main/java/com/outsourcing/domain/review/dto/request/ReviewRequest.java
  src/main/java/com/outsourcing/domain/review/dto/request/ReviewUpdateRequest.java
  src/main/java/com/outsourcing/domain/review/dto/response/ReviewReplyResponse.java
  src/main/java/com/outsourcing/domain/review/dto/response/ReviewResponse.java
  src/main/java/com/outsourcing/domain/review/entity/Image.java
  src/main/java/com/outsourcing/domain/review/entity/Review.java
  src/main/java/com/outsourcing/domain/review/entity/ReviewReply.java
  src/main/java/com/outsourcing/domain/review/repository/ImageRepository.java
  src/main/java/com/outsourcing/domain/review/repository/ReviewReplyRepository.java
  src/main/java/com/outsourcing/domain/review/repository/ReviewRepository.java
  src/main/java/com/outsourcing/domain/review/service/ReviewReplyService.java
  src/main/java/com/outsourcing/domain/review/service/ReviewService.java
Labels: ✨ feat

#75 Feat: AOP 적용
  src/main/java/com/outsourcing/common/annotation/LogTrace.java
  src/main/java/com/outsourcing/common/aspect/LogTraceAspect.java
  src/main/java/com/outsourcing/domain/order/controller/CustomerOrderController.java
  src/main/java/com/outsourcing/domain/order/controller/OwnerOrderController.java
  src/main/java/com/outsourcing/domain/order/controller/UserOrderController.java
Labels: ✨ feat

#68 Test: `UserService` 테스트 코드 작성
  src/test/java/com/outsourcing/domain/user/service/CustomerServiceTest.java
  src/test/java/com/outsourcing/domain/user/service/UserServiceTest.java
Labels: 🧪 test

#76 Chore: `application.yml` 내용 추가 및 prod로 연결
  src/main/resources/application.yml
  src/main/resources/prod/application-datasource.yml
  src/main/resources/prod/application-prod.yml
  src/main/resources/prod/application-secret.yml
Labels: ⚙️ chore

#78 Chore: schemq.sql 작성
  src/main/resources/schema.sql
Labels: ⚙️ chore

#79 Test: `StoreCustomerServiceTest` 테스트 코드 작성
  src/test/java/com/outsourcing/domain/store/service/StoreCustomerServiceTest.java
Labels: 🧪 test
